# Generated by Django 3.2.5 on 2021-08-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
